#!/usr/bin/env python3
import os
import subprocess
import sys

from api import cli


if __name__ == '__main__':
    try:
        if os.geteuid() != 0:
            subprocess.call(['sudo', sys.executable] + sys.argv)
        else:
            os.chdir(os.path.dirname(__file__))
            cli.main()
    except KeyboardInterrupt:
        raise SystemExit(1)
