#!/bin/sh
set -eu
if [ $(id -u) -ne 0 ]; then
    echo "Running with sudo..."
    sudo $0 "$@"
else
    root=$(dirname $(realpath -s $0))
    cd $root
    [ -d env ] || virtualenv -p /usr/bin/python3 env
    . env/bin/activate
    pip show -q pystache || pip install pystache
    python -m fire "$@"
fi
