#!/bin/bash
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -exuo pipefail
IFS=$'\n\t'

export DEBIAN_FRONTEND=noninteractive
export DBUS_SESSION_BUS_ADDRESS=/dev/null
export PATH=./node_modules/.bin/:$PATH

_activate() {
    set +ux
    . /opt/superdesk/env/bin/activate
    set -ux
}
locale-gen en_US.UTF-8

apt-get -y install --no-install-recommends \
git python3 python3-dev python3-venv \
build-essential libffi-dev \
libtiff5-dev libjpeg8-dev zlib1g-dev \
libfreetype6-dev liblcms2-dev libwebp-dev \
curl libfontconfig libssl-dev


repo=/opt/superdesk
if [ ! -d $repo ]; then
    mkdir $repo
    cd $repo
    git init
    git remote add origin https://github.com/superdesk/superdesk.git
else
    cd $repo
fi
unset repo

cd /opt/superdesk
repo_sha=
git fetch origin heads/master:
git checkout ${repo_sha:-FETCH_HEAD}
unset repo_sha


### Server part
# init virtualenv
env=/opt/superdesk/env
[ -d $env ] && rm -rf $env
python3 -m venv $env
unset env

_activate
pip install -U pip wheel

cd /opt/superdesk/server
time pip install -U -r requirements.txt


### Client part
# node & npm
curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
apt-get install -y nodejs
[ -f /usr/bin/node ] || ln -s /usr/bin/nodejs /usr/bin/node
npm --version
node --version

cd /opt/superdesk/client
npm install grunt-cli
time npm install

# TODO: maybe remove "--force" later
# vars are used in "webpack.config.js"
# export VIEW_DATE_FORMAT='<VIEW_DATE_FORMAT>'
# export VIEW_TIME_FORMAT='<VIEW_TIME_FORMAT>'
time \
SUPERDESK_URL='<SUPERDESK_URL>' \
SUPERDESK_WS_URL='<SUPERDESK_WS_URL>' \
SUPERDESK_RAVEN_DSN='<RAVEN_DSN>' \
IFRAMELY_KEY='<IFRAMELY_KEY>' \
grunt build --force
