#!/bin/sh
set -ex

name=superdesk-content-api
repo_remote=https://github.com/superdesk/superdesk-content-api.git

root=$(dirname $(dirname $(realpath -s $0)))
. $root/common/index.sh

_repo() {
    [ -d $repo ] || git clone --depth=1 $repo_remote $repo
}

_nginx_locations() {
    cat <<EOF
    location /pubapi {
        proxy_pass http://localhost:5050;
    }
EOF
}

_supervisor_append() {
     cat <<EOF
[program:capi]
command=/bin/sh -c '. $env/bin/activate && exec gunicorn -b 0.0.0.0:5050 wsgi'
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/capi.log
redirect_stderr=true
directory=$repo
EOF
}

do_backend() {
    _repo
    _envfile

    _venv $env
    pip install -U -r $repo/requirements.txt
}
do_prepopulate() {
    . $env/bin/activate
    cd $repo
    python content_api_manage.py app:prepopulate || true
}

do_init() { :; }
do_services() { :; }
do_finish() { :; }
do_install() { :; }

eval $action
