#!/bin/sh
set -xe

name=superdesk
repo_remote=https://github.com/superdesk/superdesk.git

root=$(dirname $(dirname $(realpath -s $0)))
. $root/common/index.sh

_envfile_end() {
    cat <<EOF >> $envfile

DEFAULT_SOURCE_VALUE_FOR_MANUAL_ARTICLES=
REUTERS_USERNAME=
REUTERS_PASSWORD=
EOF
}

_nginx_locations() {
    action=_nginx_locations $root/superdesk/content-api
}

_supervisor_adds() {
    action=_supervisor_adds $root/superdesk/content-api
}

do_backend() {
    _venv $env
    pip install -U -r $repo/server/requirements.txt

    action=do_backend $root/superdesk/content-api
    _supervisor
}

do_frontend() {
    _npm
    npm install -g grunt-cli

    cd $repo/client
    npm install
    grunt build --server='http://localhost:5000/api' --ws='ws://localhost:5100'
}

do_prepopulate() {
    . $env/bin/activate
    cd $repo/server
    python manage.py app:initialize_data
    python manage.py users:create -u admin -p admin -e 'admin@example.com' --admin

    action=do_prepopulate $root/superdesk/content-api
}

$action
services= $root/superdesk/content-api
