#!/bin/bash
set -e

repo_remote=${repo_remote:-https://github.com/superdesk/superdesk-client-core.git}

root=$(dirname $(dirname $(realpath -s $0)))
action=true . $root/superdesk-dev/core

repo_core=$repo/client-core

_repo_client() {
    echo $repo_core
}

_e2e_tests() {
    _es_snapshots

    webdriver-manager update
    time xvfb-run protractor protractor.conf.js --stackTrace --verbose\
        --baseUrl 'http://localhost'\
        --params.baseBackendUrl 'http://localhost/api'
}

do_checks() {
    _es_wait
    _chrome

    cat <<EOF >> $envfile
SUPERDESK_TESTING=true
SUPERDESK_URL=http://localhost/api
SUPERDESK_CLIENT_URL=http://localhost
SUPERDESK_WS_URL=ws://localhost
EOF
    supervisorctl restart all

    [ -z "$ci" ] && [ -z "$e2e" ] && ci=1 && e2e=1

    cd $repo_core
    export PATH=./node_modules/.bin/:$PATH

    [ -n "$ci" ] && xvfb-run grunt ci:travis
    [ -n "$e2e" ] && _e2e_tests
}

do_finish() {
    _es_snapshots
    _activate
}

eval $action
