#!/bin/bash
set -e

root=$(dirname $(dirname $(realpath -s $0)))
action=true . $root/superdesk-dev/core

repo_core=$repo/client-core
repo_remote=${repo_remote:-$repo_remote_client}

_repo_client() {
    echo $repo_core
}

_e2e_tests() {
    _es_snapshots
    specs=$([ -z "$specs" ] || echo "--specs $specs")
    # specs="--specs spec/login_spec.js"

    webdriver-manager update
    time xvfb-run protractor protractor.conf.js --stackTrace --verbose\
        --baseUrl 'http://localhost'\
        --params.baseBackendUrl 'http://localhost/api'\
        $specs
}

_chrome() {
    if grep "google-chrome-stable" $repo_core/.travis.yml; then
        _chrome_stable
    else
        # it was using before protractor 4.0
        # e2e tests are not working with "google-chrome-stable"
        # https://github.com/superdesk/superdesk-client-core/pull/1067/
        apt-get install -y --no-install-recommends unzip xvfb libgconf-2-4 chromium-browser
        cd /tmp
        wget -N --no-verbose 'https://storage.googleapis.com/chromium-browser-continuous/Linux_x64/353893/chrome-linux.zip'
        unzip -qo chrome-linux.zip
        export CHROME_BIN=$(pwd)/chrome-linux/chrome && $CHROME_BIN --version
    fi
}

do_specs() {
    cd $repo_core
    set +x
    echo "$pattern"
    find spec -type f -name "*spec*.js" | sort
    set -x
}

do_checks() {
    cd $repo_core
    export PATH=./node_modules/.bin/:$PATH

    [ -z "$npmtest" ] && [ -z "$e2e" ] && [ -z "$docs" ] && npmtest=1 && e2e=1 && docs=1
    [ -z "$npmtest" ] || time xvfb-run npm test
    [ -z "$e2e" ] || _e2e_tests
    [ -z "$docs" ] || ([ "$(grep -c no-serve tasks/options/dgeni-alive.js)" = "0" ] || grunt docs --no-serve)
}

do_finish() {
    _es_snapshots
    _chrome

    docs=1 do_checks

    echo SUPERDESK_TESTING=true  >> $envfile
    supervisorctl restart all
}

eval $action
