#!/bin/bash
set -e

root=$(dirname $(dirname $(realpath -s $0)))
action=true . $root/superdesk-dev/master

repo_core=$repo/server-core

eval "_orig$(declare -f _repo)"
_repo() {
    [ -d $repo ] && rm -rf $repo
    mkdir $repo
    cd $repo
    git init
    git remote add tmp https://github.com/naspeh-sf/superdesk.git
    git fetch tmp submodules
    git checkout tmp/submodules
    git submodule update --init

    repo=$repo_core _orig_repo
}

do_backend() {
    _venv $env
    if [ "$0" = "superdesk-dev/client-core" ]; then
        cd $repo_core/test-server
        pip install -Ur requirements.txt
    else
        cd $repo_core
        pip install -Ur requirements.txt
    fi
}

do_finish() {
    _es_snapshots
}

do_checks() {
    cd $repo_core
    _backend_checks
}

eval $action
