#!/bin/bash

root=$(dirname $(dirname $(realpath -s $0)))
action=true . $root/superdesk-dev/master

repo_core=$repo/server-core

eval "_orig$(declare -f _repo)"
_repo() {
    cd $repo
    git remote add tmp https://github.com/naspeh-sf/superdesk.git || true
    git fetch tmp submodules
    git checkout tmp/submodules

    repo=$repo_core _orig_repo
}

do_finish() {
    _es_snapshots

    . $env/bin/activate
    cd $repo_core
    pip install -r requirements.txt
}

do_checks() {
    cd $repo_core
    _backend_checks
}

eval $action
