#!/bin/bash

root=$(dirname $(dirname $(realpath -s $0)))
action=true . $root/superdesk/master

repo_backend=${repo_backend:-"$repo/server"}

_es_wait() {
    elastic=0
    while [ $elastic -eq 0 ]
    do
        curl -s "http://localhost:9200" 2>&1 > /dev/null \
            && elastic=1 \
            || echo "waiting for elastic..."
        sleep 1
    done
}

_es_init() {
    es_backups=/tmp/es-backups
    if [ ! -d "$es_backups" ]; then
        mkdir $es_backups
        chown elasticsearch:elasticsearch $es_backups
    fi

    echo 'log4j.rootLogger=OFF' > /etc/elasticsearch/logging.yml
    config='/etc/elasticsearch/elasticsearch.yml'
    cat << EOF > $config
$pattern
network.bind_host: 0.0.0.0
node.local: true
discovery.zen.ping.multicast: false
index.refresh_interval: 30s
index.store.type: memory
index.number_of_replicas: 0
path.repo: $es_backups

# Next setting break behave tests
# index.number_of_shards: 1
EOF

    systemctl restart elasticsearch
    _es_wait
    curl -XPUT 'http://localhost:9200/_snapshot/backups' \
        -d '{"type": "fs", "settings": {"location": "/tmp/es-backups"}}'
}

_mongo_init() {
    path=/tmp/mongodb
    [ -d $path ] || mkdir $path
    chown mongodb:mongodb $path
    cat << EOF > /etc/mongod.conf
storage:
  dbPath: $path
  journal:
    enabled: false
  engine: wiredTiger

net:
  port: 27017
  bindIp: 0.0.0.0
EOF
    systemctl restart mongod
}

_db_uninstall() {
    [ $(systemctl list-units | grep -c elasticsearch) = "0" ] && return 0
    systemctl stop elasticsearch mongod || true
    systemctl disable elasticsearch mongod || true
    apt-get -y remove \
        openjdk-8-jre-headless \
        elasticsearch \
        mongodb-org-server
    apt-get -y autoremove
}

_db_external() {
    [ -n "$lxc_data" ] || exit 1
    db_name=${db_name:-$(hostname)}
    MONGO_URI="mongodb://$lxc_data/$db_name"
    ELASTICSEARCH_URL="http://$lxc_data:9200"
    ELASTICSEARCH_INDEX="$db_name"

    _envfile
    supervisorctl restart all
}

_db_init() {
    if [ -n "$lxc_data" ]; then
        systemctl stop elasticsearch mongod
        _db_external
    else
        _es_init
        _mongo_init

        # initialize directories in "/tmp", etc.
        # TODO
        # hook=/opt/lxc-hooks/start.sh
        # hook_dir=$(dirname $hook)
        # mkdir -p $hook_dir
        # echo "mkdir /tmp/mongodb" > $hook
        # chmod +x $hook
    fi
}

_checks_init() {
    export SUPERDESK_TESTING=true
    _db_init
    supervisor_tpl=$root/superdesk-dev/supervisor.tpl _supervisor
}

_chrome_stable() {
    [ "$(dpkg -l | grep -c google-chrome-stable)" = "0" ] || return 0

    wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
    echo "deb http://dl.google.com/linux/chrome/deb/ stable main" \
        > /etc/apt/sources.list.d/google.list
    apt-get update
    apt-get install -y --no-install-recommends xvfb google-chrome-stable
}

_chrome() {
    _chrome_stable
}

_backend_checks() {
    cd $repo_backend
    _activate

    # run flake8 with on jobs, because it could lock the build for ever
    [ -z "$flake8" ] || flake8 --jobs=1

    [ -z "$nose" ] || time nosetests -v --with-id

    feature=(./features/*.feature)
    [ -f $feature ] || behave=
    [ -z "$behave" ] || time behave --format progress2 --logging-clear-handlers --logcapture
}

_client_checks() {
    cd $repo/client
    [ -z "$npmtest" ] || time npm test
}

eval "orig_$(declare -f do_install)"
do_install() {
    if [ -d $repo ]; then
        # FIXME: clean lock files when installing new container
        # started appears in base container after ZFS snaphsot usage
        rm /var/lib/apt/lists/lock || true
        rm /var/lib/dpkg/lock || true
        rm /var/cache/apt/archives/lock || true
    fi

    orig_do_install
}

do_finish() {
    _chrome

    _activate
    cd $repo/server
    time pip install -r dev-requirements.txt
}

do_checks() {
    if [ -z "$nose" ] && [ -z "$behave" ] && [ -z "$flake8" ] && [ -z "$npmtest" ]; then
        nose=1
        behave=1
        flake8=1
        npmtest=1
    fi
    _checks_init
    _backend_checks
    _client_checks
}

do_docs() { :; }

do_www() {
    _db_init
    sample_data=1 do_prepopulate

    do_docs || true
}

eval $action
