#!/bin/bash

name=superdesk
repo_remote=https://github.com/superdesk/superdesk-ntb.git
repo_branch=tags/v1.0

root=$(dirname $(dirname $(realpath -s $0)))
. $root/superdesk-dev/master

do_prepopulate() {
    . $env/bin/activate
    cd $repo/server
    python manage.py app:initialize_data
    python manage.py users:create -u admin -p admin -e 'admin@example.com' --admin

    action=do_prepopulate $root/superdesk/content-api
}
