#!/bin/bash
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -exuo pipefail
#IFS=$'\n\t'

export PATH=./node_modules/.bin/:$PATH
DEBIAN_FRONTEND=noninteractive
DBUS_SESSION_BUS_ADDRESS=/dev/null

_activate() {
    set +ux
    . /opt/liveblog/env/bin/activate
    set -ux
}

_skip_install() {
    dpkg -l | grep '^ii.*'$1 && [ -z "" ]
}
locale-gen en_US.UTF-8

apt-get -y install --no-install-recommends \
git python3 python3-dev python3-venv \
build-essential libffi-dev \
libtiff5-dev libjpeg8-dev zlib1g-dev \
libfreetype6-dev liblcms2-dev libwebp-dev \
curl libfontconfig libssl-dev


repo=/opt/liveblog
if [ ! -d $repo ]; then
    mkdir $repo
    cd $repo
    git init
    git remote add origin https://github.com/liveblog/liveblog.git
else
    cd $repo
fi

cd $repo
repo_ref=heads/master
repo_sha=
git fetch origin $repo_ref:
git checkout ${repo_sha:-FETCH_HEAD}
unset repo_sha
unset repo repo_ref


### Server part
# init virtualenv
env=/opt/liveblog/env
[ -d $env ] && rm -rf $env
python3 -m venv $env
echo 'export PATH=./node_modules/.bin/:$PATH' >> $env/bin/activate
unset env

_activate
pip install -U pip wheel

cd /opt/liveblog/server
time pip install -U -r requirements.txt


### Client part
### node & npm
if ! _skip_install nodejs; then
    curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
    apt-get install -y nodejs
fi

[ -f /usr/bin/node ] || ln -s /usr/bin/nodejs /usr/bin/node
npm --version
node --version

cd /opt/liveblog/client
npm i grunt-cli
npm i bower
time npm install
time bower --allow-root install

# export VIEW_DATE_FORMAT='<VIEW_DATE_FORMAT>'
# export VIEW_TIME_FORMAT='<VIEW_TIME_FORMAT>'
time \
SUPERDESK_URL='<SUPERDESK_URL>' \
SUPERDESK_WS_URL='<SUPERDESK_WS_URL>' \
SUPERDESK_RAVEN_DSN='<RAVEN_DSN>' \
IFRAMELY_KEY='<IFRAMELY_KEY>' \
EMBEDLY_KEY='<EMBEDLY_KEY>' \
grunt build --force
