#!/bin/bash
set -ex

name=${name:-superdesk}
repo_remote=${repo_remote:-https://github.com/superdesk/superdesk.git}

. common/index.sh

_envfile_append() {
    cat <<EOF
# Superdesk custom
SECRET_KEY=${SECRET_KEY-"$(python -c 'import uuid; print(uuid.uuid4())')"}
REUTERS_USERNAME=${REUTERS_USERNAME-''}
REUTERS_PASSWORD=${REUTERS_PASSWORD-''}
EOF
}

_nginx_locations() {
    cat <<EOF
location /contentapi {
    proxy_pass http://localhost:5050;
    proxy_set_header Host $host;
    expires epoch;
}
EOF
}

_supervisor_append() {
     cat <<EOF
[program:capi]
command=/bin/sh -c '. $env/bin/activate && exec gunicorn -b 0.0.0.0:5050 content_api.wsgi'
autostart=true
autorestart=true
stdout_logfile=/var/log/$name/capi.log
redirect_stderr=true
directory=$repo/server
EOF
}

_sample_data() {
    [ -z "$sample_data" ] || sample_data='--sample-data'
    [ "$(python manage.py app:initialize_data --help | grep -c -- --sample-data)" = "0" ] && sample_data=
}


do_frontend() {
    _activate # env vars
    _npm

    cd $(_repo_client)
    npm install grunt-cli
    time npm install

    # update translations if "client/po" directory exists
    po_dir=$repo/client/po
    if [ -d $po_dir ] && [ "$po_dir" = "$(pwd)/po" ]; then
        grunt nggettext_extract
        grunt nggettext_compile
    fi

    #TODO: remove --force later
    time grunt build --server='http://localhost:5000/api' --ws='ws://localhost:5100' --force
    echo "\033[0m"
}

do_prepopulate() {
    cd $repo/server

    _activate
    _sample_data

    python manage.py app:initialize_data $sample_data
    python manage.py users:create -u admin -p admin -e 'admin@example.com' --admin
}

eval $action
