#!/bin/bash
set -e

action=true . superdesk-dev/core

repo_core=$repo/client-core
repo_remote=${repo_remote:-$repo_remote_client}

_repo_client() {
    echo $repo_core
}

_e2e_tests() {
    specs=$([ -z "$specs" ] || echo "--specs $specs")
    # specs="--specs spec/login_spec.js"

    npm i protractor-flake
    webdriver-manager update

    time xvfb-run -a -s "-ac -screen 0 1920x1080x24"\
        protractor-flake --max-attempts=2 --\
        protractor.conf.js --stackTrace --verbose\
        --baseUrl 'http://localhost'\
        --params.baseBackendUrl 'http://localhost/api'\
        $specs
}

_chrome() {
    if grep "google-chrome-stable" $repo_core/.travis.yml; then
        _chrome_stable
    else
        # it was using before protractor 4.0
        # e2e tests are not working with "google-chrome-stable"
        # https://github.com/superdesk/superdesk-client-core/pull/1067/
        apt-get -y remove google-chrome-stable
        apt-get install -y --no-install-recommends unzip xvfb libgconf-2-4 chromium-browser
        cd /var/tmp
        wget -N --no-verbose 'https://storage.googleapis.com/chromium-browser-continuous/Linux_x64/353893/chrome-linux.zip'
        unzip -qo chrome-linux.zip

        export CHROME_BIN=$(pwd)/chrome-linux/chrome
        $CHROME_BIN --version
    fi
}

do_backend() {
    _venv
    cd $repo_core/test-server
    time pip install -r requirements.txt
    pip install gunicorn
}

do_specs() {
    cd $repo_core
    set +x
    echo "$pattern"
    find spec -type f -name "*spec*.js" -printf $'%p\t%s\n' | sort -k2,2n
    set -x
}

do_checks() {
    _checks_init
    _activate

    cd $repo_core

    [ -z "$npmtest" ] && [ -z "$e2e" ] && [ -z "$docs" ] && npmtest=1 && e2e=1 && docs=1
    [ -z "$npmtest" ] || time xvfb-run -a npm test
    [ -z "$e2e" ] || _e2e_tests
    [ -z "$docs" ] || do_docs
}

do_docs() {
    cd $repo_core
    [ -z "$(grep no-serve tasks/options/dgeni-alive.js)" ] || grunt docs --no-serve
}

eval $action
