#!/bin/bash
set -e

action=true . superdesk-dev/master

repo_remote_server=https://github.com/superdesk/superdesk-core.git
repo_remote_client=https://github.com/superdesk/superdesk-client-core.git
repo_core=$repo/server-core
repo_backend=$repo_core
repo_main_branch=${repo_main_branch:-master}
repo_pair_branch=${repo_pair_branch:-master}

eval "_orig$(declare -f _repo)"
_repo() {
    [ -d $repo ] && rm -rf $repo
    mkdir $repo
    cd $repo
    git init
    git remote add origin https://github.com/superdesk/superdesk.git
    git fetch origin $repo_main_branch
    git checkout origin/$repo_main_branch
    sed -i -re 's/("superdesk-core":).*/\1 "file:..\/client-core"/' client/package.json
    sed -i 's/.*superdesk-core.git.*/-e ..\/server-core/' server/requirements.txt

    if [ "$0" = "superdesk-dev/client-core" ]; then
        pair=server-core
        pair_remote=$repo_remote_server
    else
        pair=client-core
        pair_remote=$repo_remote_client
    fi
    mkdir $pair
    cd $pair
    git init
    git remote add origin $pair_remote
    git fetch origin $repo_pair_branch
    git checkout origin/$repo_pair_branch

    repo=$repo_core _orig_repo
}

do_backend() {
    _venv
    cd $repo_backend
    time pip install -r requirements.txt

    # here are some deployment dependencies: gunicorn, etc.
    cd $repo/server
    time pip install -r requirements.txt
}

do_checks() {
    if [ -z "$nose" ] && [ -z "$behave" ] && [ -z "$flake8" ] && [ -z "$docs" ]; then
        docs=1
        nose=1
        behave=1
        flake8=1
    fi

    _activate
    [ -z "$docs" ] || do_docs

    _checks_init
    _backend_checks
}

do_docs() {
    cd $repo_core/docs
    make html
    [ ! -d $repo/client/dist ] || cp -Tr _build/html $repo/client/dist/docs
}

eval $action
